name: Build and Release Plugin

on:
  push:
    tags:
      - "*"

jobs:
  buildAndRelease:
    name: Build Plugin
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP 7.4
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"
          coverage: none
          tools: composer:v2

      - name: Install dependencies and build
        run: |
          composer install --no-dev --optimize-autoloader

      - name: Create plugin zip
        run: |
          rsync -rc --exclude-from=.distignore ./ metadata-viewer/ --delete --delete-excluded
          zip -r metadata-viewer.zip metadata-viewer/
          rm -rf metadata-viewer

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: metadata-viewer
          path: metadata-viewer.zip
          retention-days: 30

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: metadata-viewer.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # TODO: Uncomment when ready to deploy to WordPress.org
    #   - name: WordPress Plugin Deploy
    #     id: deploy
    #     uses: 10up/action-wordpress-plugin-deploy@stable
    #     with:
    #       generate-zip: true
    #     env:
    #       SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
    #       SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
    #       SLUG: metadata-viewer
